# **Numpy**

In [1]:
import numpy as np

### **Unidimensional Array**

In [21]:
array = np.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


### **Bidimensional Array**

In [19]:
array_2d = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])

print(array_2d)

[[1 2 3 4 5]
 [5 4 3 2 1]]


### **Random Numbers**

In [20]:
rdn = np.random.random((3, 3))

print(rdn)

[[0.84807683 0.78695863 0.633453  ]
 [0.70985086 0.27943798 0.37838833]
 [0.89042577 0.69179038 0.55715998]]
